version: "3"
services:
    app:
        container_name: greengrocer_app
        build:
          context: .
          dockerfile: Dockerfile.dev
        ports:
          - "3000:3000"
          - "8081:8081"
        volumes:
          - .:/usr/local/app
          # These volumes are to prevent overwriting node_modules in the container when we bind mount host directory, which is not expected to have node_modules
          # May need to exclude host node_modules and delete if present: https://burnedikt.com/dockerized-node-development-and-mounting-node-volumes/
          - client_nodemodules:/usr/local/app/node_modules
          - server_nodemodules:/usr/local/app/server/node_modules
        depends_on:
          - db
        command: sh -c "npm run prod"
    db:
        container_name: greengrocer_db
        image: postgres
        ports:
          - "5432:5432"
        volumes:
          - db:/var/lib/postgresql/data
        environment:
          - POSTGRES_USER=${POSTGRES_USER}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          - POSTGRES_DB=${POSTGRES_DB}
volumes:
  db:
  client_nodemodules:
  server_nodemodules:
  