FROM node:lts
WORKDIR /usr/local/app
RUN pwd
COPY . ./
RUN npm install
RUN npm run build
WORKDIR /usr/local/app/server
RUN pwd
RUN npm install
# WORKDIR sets dir for docker-compose commands to run
RUN npm run prod
EXPOSE $PORT